version: "3.9"

services:
  frontend:
    container_name: fe
    image: flab/fe:1.0.0
    build: ./src/frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - backend
  backend:
    container_name: be
    image: flab/be:1.0.0
    build: ./src/backend
    ports:
      - '8000:8000'

  # frontend:
  #   build: ./frontend
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./frontend:/app
  #   working_dir: /app
  #   environment:
  #     - NEXT_PUBLIC_API_URL=http://localhost:8080